#!/bin/bash
set -e
set -o pipefail

awk -- '
    BEGIN {
        multiline_error = 0;
    }

    /^> Task :.+ FAILED$/ {
        multiline_error = 1;
    }

    /^FAILURE: Build failed with an exception\.$/ {
        multiline_error = 0;
    }

    multiline_error {
        print;
    }

' "$1" | sed -Ee "s|$2/||"
