#!/bin/sh
set -e

if [ "$1" = "--dry-run" ]
then
 echo "dry run" 1>&2
 mode=dryrun
 gitcmd="echo git"
else
 mode=for_real
 gitcmd="git"
fi

cd ../refactoring-to-kotlin-code

tagfmt='*.[0-9]*'

git tag -l "$tagfmt" | xargs $gitcmd tag -d >/dev/null
git log --branches --not --branches="[m]aster" --topo-order --format=oneline | awk '
    /[0-9a-f]{32} (r[0-9]+|[a-z_]+)([.][0-9]+)+ :/ {
      linerev = $2
      if (linerev != rev) {
         rev = linerev
         print $2, $1
      }
    }
' | xargs -n 2 $gitcmd tag -f
