#!/bin/sh
set -e

if [ "$1" = "--for-real" ]
then
 echo "for real" 1>&2
 mode=for_real
 gitcmd="git"
else
 echo "dry run" 1>&2
 mode=dryrun
 gitcmd="echo git"
fi

cd ../refactoring-to-kotlin-code

tagfmt='*.[0-9]*'

git tag -l "$tagfmt" | xargs $gitcmd tag -d
git log --branches --topo-order --format=oneline | awk '
    /[0-9a-f]{32} (r[0-9]+|[a-z_]+)([.][0-9]+)+ :/ {
      linerev = $2
      if (linerev != rev) {
         rev = linerev
         print $2, $1
      }
    }
' | xargs -n 2 $gitcmd tag -f

if [ "$mode" = "for_real" ]
then
    echo
    echo Current tags:
    git tag --list "$tagfmt" | sort -V
fi
