#!/bin/sh
set -e

if [ "$1" = "--for-real" ]
then
 echo "for real" 1>&2
 mode=for_real
 gitcmd="git"
else
 echo "dry run" 1>&2
 mode=dryrun
 gitcmd="echo git"
fi

cd ../refactoring-to-kotlin-code

git tag -l 'r[0-9]*' | xargs $gitcmd tag -d
git log --format=oneline | awk '
    /[0-9a-f]{32} r([0-9|.]+) :/ {
      linerev = substr($2,2) + 0 # force a numeric comparison
      if (linerev != rev) {
         rev = linerev
         print $2, $1
      }
    }
' | xargs -n 2 $gitcmd tag -a -m "tag generated automatically by retag-worked-example script" -f

if [ "$mode" = "for_real" ]
then
    git tag --list 'r[0-9]*' | sort -V
fi
