Thank you to Hadi Hariri for suggesting to O'Reilly that we should write a book, to Zan McQuade for believing him.
Thank you to our editor Sarah Grey, who had to live with the consequences, and Kerin Forsyth and Kate Galloway for tidying everything up and producing an actual book.

Many friends and colleagues, and some lovely strangers, reviewed drafts ranging from early and uncoordinated to tantalizingly nearly complete.
Thank you to
Yana Afanasyeva,
Jack Bolles,
David Denton,
Bruce Eckel,
Dmitry Kandalov,
Kevin Peel,
James Richardson,
Ivan Sanchez,
Jordan Stewart,
Robert Stoll,
Christoph Sturm,
Łukasz Wycisk,
and Daniel Zappold
and to our technical reviewers,
Uberto Barbini,
James Harmon,
Mark Maynard,
and Augusto Rodriguez.
We really appreciate all your suggestions, encouragement, and candor.

Extreme Programming revolutionized the way that write software--we all owe a debt of gratitude to Ward Cunningham and Kent Beck.
Thank you also to Martin Fowler, without whom this book might not have been written.
In the UK the eXtreme Tuesday Club has been innovating on these ideas since 1999, and has attracted a cabal of developers.
We are lucky to have worked with, and learned from, many talented members of this group.
If you have a problem, if no one else can help, and if you can find them, maybe you can hire them.


==== Duncan's Bit

I don't think my wife will ever understand what I do for a living, and there's no chance that she will read the rest of this book, but she will probably get this far.
So thank you, Jo McGregor, for putting up with me writing rather than spending time with you, and talking about writing when I was spending time with you.
I couldn't have done it without your support and encouragement.
Thank you also to our two wonderful sons, Callum and Alistair, who make us so proud.

Thank you to Vickie Kennish for taking a keen interest in becoming the mother of an author, checking on progress during our COVID lockdown walks.
My late father, John, would I'm sure have played it more casual, but be bragging about the book to his friends.
Also gone but not forgotten is our beautiful cat Sweet Pea, who kept me company through most of the writing but died just before it was finished.

The friendship and support of Robin Helliwell has been a constant throughout my adult life.
Likewise, my sister Lucy Seal, and many other family members too numerous to list individually.
In my professional life, in addition to those who gave feedback, thank you to Alan Dyke, Richard Care, and Gareth Sylvester-Bradley, all influential and supportive beyond the call of duty.


==== Nat's Bit

When I told my wife, Lamaan, that I was planning to write another book, her immediate reaction was not one of horror.
For that, and for her constant encouragement, I owe her many thanks.

Hat tip to my sister, Lois Pryce, and brother-in-law, Austin Vince, whose motorcycle journeys, books, and films inspired the overland travel planning application used in the worked example code.

And thanks to Oliver and Alex.
Now that the book is finished, I am once again available for consultancy in music and games programming.
