[preface]
== Preface

include::our-preface.asciidoc[]

=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This element signifies a tip or suggestion.
====

[NOTE]
====
This element signifies a general note.
====

[WARNING]
====
This element indicates a warning or caution.
====

[[using-code-examples]]
=== Using Code Examples

Most of the code examples((("code examples, obtaining and using"))) in the book (the ones from the refactoring sections) can be accessed online on GitHub.
The reference is immediately after the code, like this:

// begin-insert: table-reader.1:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt
[source,kotlin]
----
class TableReaderAcceptanceTests {
    @Test
    fun test() {
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://github.com/java-to-kotlin/code/blob/table-reader.1/src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt">
        table-reader.1:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt
    </a>
</div>
++++
// end-insert

If you are reading this on a device, following the reference should take you to that version of the file on GitHub.
On real paper, you can click all you like; nothing will happen, sorry.
But you can reconstitute the link as follows.
Take the reference text, in this case:

`table-reader.1:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt`

replace the `:` separator with a `/` and add to the root URL `https://github.com/java-to-kotlin/code/blob/` to get

**`https://github.com/java-to-kotlin/code/blob/table-reader.1/src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt`**

Open this URL in a web browser and it will take you to the same place as the electronic version.

In Git, the different code examples (these sometimes span multiple chapters) evolve in separate branches (in this case a branch named "table-reader"), and the steps are tagged (`table-reader.1` is the tag in this case).
The GitHub link is to code with that tag, so you can view that file and the others in the example at that version.
You can also select other tags to see the different versions, and different branches to see different examples.
For quicker navigation, you can clone the repository, open it in IntelliJ, and use the Git tool window to switch branches and versions.

[WARNING]
====
The code examples are not real!
The codebase builds and passes its tests, but it is fictional.
There are places where the examples don't join up properly, and others where if you peek behind the curtain you will see us wiggling the levers.
We have tried to be honest, but prefer to ship!
====

If you have a technical question or a problem using the code examples, please visit https://java-to-kotlin.dev[the book's website] or send an email to pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

This book is here to help you get your job done. In general, if example code is offered with this book, you may use it in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require [.keep-together]#permission#.

We appreciate, but generally do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “_Java to Kotlin_ by Duncan McGregor and Nat Pryce (O’Reilly). Copyright 2021 Duncan McGregor and Nat Pryce, 978-1-492-08227-9.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a class="email" href="mailto:permissions@oreilly.com"><em>permissions@oreilly.com</em></a>].

=== O'Reilly Online Learning

[role = "ormenabled"]
[NOTE]
====
For more than 40 years, pass:[<a href="http://oreilly.com" class="orm:hideurl"><em class="hyperlink">O’Reilly Media</em></a>] has provided technology and business training, knowledge, and insight to help companies succeed.
====

Our unique network of experts and innovators share their knowledge and expertise through books, articles, conferences, and our online learning platform. O’Reilly’s online learning platform gives you on-demand access to live training courses, in-depth learning paths, interactive coding environments, and a vast collection of text and video from O'Reilly and 200+ other publishers. For more information, please visit pass:[<a href="http://oreilly.com" class="orm:hideurl"><em>http://oreilly.com</em></a>].  

=== How to Contact Us

Please((("questions and comments")))((("comments and questions"))) address comments and questions concerning this book to the publisher:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (in the United States or Canada)</li>
  <li>707-829-0515 (international or local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

We have a web page for this book, where we list errata, examples, and any additional information. You can access this page at link:$$https://oreil.ly/java-to-kotlin$$[].

++++
<!--Don't forget to update the link above.-->
++++

Email pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>] to comment or ask technical questions about this book.

For more information about our books, courses, conferences, and news, see our website at link:$$http://www.oreilly.com$$[].

Find us on Facebook: link:$$http://facebook.com/oreilly$$[]

Follow us on Twitter: link:$$http://twitter.com/oreillymedia$$[]

Watch us on YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Acknowledgments

include::acknowledgements.asciidoc[]
