[[java-to-kotlin-projects]]
== Java to Kotlin Projects

++++
<blockquote data-type="epigraph">
<p class="lrgquote">What is the first step of the journey from pure Java to a mixed and then increasingly Kotlin codebase?</p>
</blockquote>
++++

=== Strategy

The((("Java Way to Kotlin Way", "strategy behind Java to Kotlin projects"))) first time we, Nat and Duncan, introduced Kotlin to a Java codebase, we were members of a small team that included six developers, building a relatively greenfield project.
We had already deployed some web applications with Kotlin, but our enterprise architects insisted that we write the new system in Java 8.
This was shortly after Kotlin 1.0 had been released, but before Google announced that Kotlin was an official language for Android, so the architects were understandably wary about committing to a language with an uncertain future for a strategic system that they expected to be around for decades.

In Java, we leaned toward a functional approach, designing the core application domain model as immutable data types transformed by pipelines.
However, we kept bumping into Java's limitations: the verbosity required to implement immutable value types, the distinction between primitive and reference types, null references, and Streams lacking common higher-order functions.
Meanwhile, we could see Kotlin being adopted at an ever-increasing rate across the industry and even within the company.
When we saw Google's announcement, we decided to start converting our Java to Kotlin.

Our judgment was that starting in the core domain model would give us the biggest bang for our buck.
Kotlin's data classes shrank the code significantly, in some cases replacing hundreds of lines of code with a single declaration.
We started carefully, using IntelliJ to convert a small value class that had no dependencies on other classes beyond those in the standard library, and examined how that affected the rest of our Java codebase.
It had no effect at all!
Emboldened by this success, we picked up the pace.
Whenever a new feature needed changes to a Java domain model class, we would first convert it to a Kotlin data class, commit the conversion, and then implement the feature.

As more of the domain model logic became pure Kotlin, we were able to make better use of Kotlin features.
For example, we replaced calls to the Stream API with Kotlin's standard functions on collections and sequences.
The biggest improvement though, was replacing our use of Java's Optional type with nullable references.
This simplified our code and gave us greater confidence in its null safety.

Another project in the company adopted Kotlin for a different reason.
They had a mature Java system that was built on a dependency injection framework.
The developers found that the framework's use of reflection and annotations made the code difficult to understand and navigate in the IDE.
Kotlin's lightweight syntax for closures offered a way to define the structure of their application and distinguish between object graphs instantiated for the whole application, for each HTTP request, or for each database transaction.
They gradually refactored the underpinnings of their system from a framework that obscured the architecture to a style that composed functions and made the architecture visible in the code.
This work became the https://http4k.org[http4k] web programming toolkit.

As these two examples show, your choice of starting point should depend on a number of factors, including why your team is adopting Kotlin, how large the codebase is, and how frequently it changes.
You know your project and can decide what is most important to change.

If you are choosing Kotlin for its language features, it makes sense to convert the classes you are working in most frequently, as we did in our first project.
If you are choosing Kotlin to use a specific library, then it makes sense to start writing Kotlin against the API, annotate it to make your Kotlin code convenient to the Java code in the rest of the app, and continue from there.

In a small team it’s easy to establish the Kotlin coding style for your system (beyond the standard style guide), for instance, error handling conventions, how code is to be organized into files, what should be a top-level declaration and what should be in an object, and so on.

Above a certain size, you run the risk of Kotlin code becoming inconsistent as people establish their own conventions in different parts of the system.
So it may be worth starting with a small subteam working in one area of the system, who establish conventions and build up a body of example code.
Once there are some established conventions, you can expand the effort to the rest of the team and other parts of the system.

[role="pagebreak-before"]
In the rest of this book, we will examine in detail how to progress, how to keep your Java code maintainable while you are introducing Kotlin that it depends upon, and how to take advantage of Kotlin's features to simplify the code further after IntelliJ has performed its conversion magic.
But all that follows the first small step.

=== Adding Kotlin Support to a Java Build

If((("Java Way to Kotlin Way", "adding Kotlin support to Java builds", id="JWKWsupport02")))((("Gradle build configuration", id="gradle02"))) we want to refactor our Java to Kotlin, the first change we must make is to give ourselves the ability to write Kotlin code in our codebase.
Happily, the Kotlin build tools and IDE make this very straightforward.
It takes a few additional lines in our Gradle build configuration for it to compile Kotlin as well as Java.
IntelliJ((("IntelliJ IDE", "adding Kotlin support to Java builds"))) will pick up that configuration when we resync the build file, allowing us to navigate, autocomplete, and refactor across both languages almost seamlessly.

To add Kotlin to our Gradle build, we need to add the Kotlin plug-in.
There is a different plug-in for each target that Kotlin supports (JVM, JavaScript, and native code), and a plug-in for building multiplatform projects.
Because we have a Java project, we can ignore other platforms and use the Kotlin JVM plug-in.

We also need to add the Kotlin standard library to our dependencies and specify the minimum JVM version that the output bytecode will support.
Our project targets JDK 11 (the latest LTS at the time of writing).
At the time of writing, the Kotlin compiler can generate bytecode compatible with JDK 1.6 or JDK 1.8. JDK 1.8 bytecode is more efficient and runs fine on JDK 11, so we will pick that.

[WARNING]
.Kotlin Versions
====
The((("Kotlin", "versions"))) Kotlin language and standard library are still maturing, but JetBrains policy is to provide a clear migration path.
The current version of Kotlin was 1.3 when we started writing this book.
As we finish it, 1.5 has just been released, deprecating some standard APIs used in our code examples!
We have chosen not to migrate to their replacements, so that the code is able to run on Kotlin 1.4 and 1.5.
====

Here are the relevant parts of our `build.gradle` before the changes:

// begin-insert: projects.0:build.gradle#java_build
[source,groovy]
----
plugins {
    id("java")
}

java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11
... and other project settings ...

dependencies {
    implementation "com.fasterxml.jackson.core:jackson-databind:2.10.0"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.0"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.0"
    ... and the rest of our app's implementation dependencies

    testImplementation "org.junit.jupiter:junit-jupiter-api:5.4.2"
    testImplementation "org.junit.jupiter:junit-jupiter-params:5.4.2"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.5.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.4.2"
    ... and the rest of our app's test dependencies
}

... and the rest of our build rules
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=2.1&amp;show=file">Example 2.1 [projects.0:build.gradle]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=2.1&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

After we have added the Kotlin plug-in, our build file looks like this:

// begin-insert: projects.1:build.gradle#kotlin_plugin
[source,groovy]
----
plugins {
    id 'org.jetbrains.kotlin.jvm' version "1.5.0"
}

java.sourceCompatibility = JavaVersion.VERSION_11
java.targetCompatibility = JavaVersion.VERSION_11
... and other project settings ...

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    ... and the rest of our app's dependencies
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile) {
    kotlinOptions {
        jvmTarget = "11"
        javaParameters = true
        freeCompilerArgs = ["-Xjvm-default=all"]
    }
}

... and the rest of our build rules
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=2.2&amp;show=file">Example 2.2 [projects.1:build.gradle]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=2.2&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert:

Given those changes, we can rerun our build, and see that...

...the build still works!

If we resync the Gradle project in IntelliJ (this may happen automatically on saving), we can run our tests and programs within the IDE.

Our tests still pass, so we haven't broken anything, but neither have we proved that we can use Kotlin in our project.
Let's test that by writing a "hello world" program.
We create a file, __HelloWorld.kt__, in the root package of our Java source tree, __src/main/java__:

.HelloWorld.kt
// begin-insert: projects.2:src/main/java/HelloWorld.kt
[source,kotlin]
----
fun main() {
    println("hello, world")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=2.3&amp;show=file">Example 2.3 [projects.2:src/main/java/HelloWorld.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=2.3&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

[TIP]
.Where to Put Kotlin Source
====
The((("Kotlin", "source placement"))) Kotlin build plug-in adds additional source roots, _src/main/kotlin_ and __src/test/kotlin__, and compiles Kotlin source files found in any of their subdirectories.

It will also compile Kotlin source found in Java source trees, in particular _src/main/java_ and __src/test/java__.
Although you can separate your source files by language, putting Java files in the _java_ directories and Kotlin into _kotlin_, in practice your authors don't bother.
It's nice to be able to look into a directory and see all the source for the corresponding package rather than casting around the filesystem.
To make this work, though, we keep Kotlin source in directories mirroring the package structure rather than taking advantage of Kotlin's ability to have files in a single directory but multiple [.keep-together]#packages#.

In a similar vein, while Kotlin does allow multiple public classes to be defined in a single class, when we are mixing Java and Kotlin in a project, we tend to stick to one class per file for consistency.
====

We can run that within the IDE by clicking the little green arrow in the lefthand margin next to `fun main()`.

We can run our build and then run it from the command line with the `java` command.
Compiling the source file named _HelloWorld.kt_ creates a Java class file named `HelloWorldKt`.
We'll look into how Kotlin source gets translated into Java class files in more detail later, but for now, we can run our program with the `java` command, like so:

[source,text]
----
$ java -cp build/classes/kotlin/main HelloWorldKt
hello, world
----

It lives!

Let's delete __HelloWorld.kt__—it's done its job—commit and push.

We now have the _option_ to use Kotlin in our project; the first part of this chapter gives some pointers to _where_ to start using it.((("", startref="gradle02")))

[role="pagebreak-before less_space"]
.Other Build Systems
****
We've((("Java Way to Kotlin Way", "build systems other than Gradle"))) chosen to show the changes necessary to add Kotlin support to a Gradle build here, but you can use Maven or Ant by following the instructions provided in the Tools section of https://oreil.ly/bWi9n[the Kotlin documentation].
This also gives instructions for using the command-line compiler, `kotlinc`.

If you use Gradle, there is the option to use Kotlin, rather than the traditional Groovy, as the build definition language.
This has the advantage of providing better tool support through strong typing, at the expense of having to translate historical StackOverflow answers into a new language.

As we are Java and Kotlin developers rather than Java and Groovy developers, your authors start new projects with the Kotlin DSL, but we don't feel the need to convert existing Groovy builds, at least not immediately.
As with the Java and Kotlin in production code, we can mix and match Kotlin and Groovy in our build, so this is a conversion that we can take our time over.
We don't recommend that you switch your build from Groovy to Kotlin as your first act of conversion, and certainly don't look to us to write a Groovy to Kotlin Gradle book!((("", startref="JWKWsupport02")))
****

=== Moving On

We expect the technical information in this chapter to date very quickly, as neither Gradle nor its plug-ins have a very stable interface.
Your current Java build file is also almost certainly incompatible with our example in some crucial way.
Despite this, though, adding Kotlin to a Java build is generally straightforward.

Devising a strategy for moving code from Java to Kotlin is more complicated and context specific.
Or at least differently complicated and context specific.
Individual projects should examine where Java is and isn’t working for them, and where using Kotlin would alleviate problems and improve the code.
You might choose to dive in and write some Kotlin from scratch, or to convert an existing Java class to Kotlin.
In the spirit of this book, the latter is the approach we'll take in pass:[<a data-type="xref" href="#java-to-kotlin-classes" data-xrefstyle="chap-num-title">#java-to-kotlin-classes</a>].

