[[classes-to-functions]]
== Classes to Functions

++++
<blockquote data-type="epigraph">
<p>Object-oriented programmers are adept at solving problems by creating types.
Functional programmers tend to augment existing types with functions.
How far can we go without defining new types?</p>
</blockquote>
++++

In pass:[<a data-type="xref" data-xrefstyle="chap-num-title" href="#encapsulated-collections-to-typealiases">#encapsulated-collections-to-typealiases</a>], we saw the advantages of working with raw collections, and in pass:[<a data-type="xref" data-xrefstyle="chap-num-title" href="#interfaces-to-functions">#interfaces-to-functions</a>], we looked at using built-in function types rather than creating new ones.
In this chapter, we'll apply the lessons we've learned to write some Kotlin from scratch.

Even in these days of REST APIs and webhooks, much of automatic business-to-business communication is in the form of tabular text data exchanged by((("Secure File Transfer Protocol (SFTP)"))) Secure File Transfer Protocol (SFTP).
Travelator has to import data for campsite locations, points of interest, unsettled bills, and more, all in regular rows and columns, with different  column separators, and with and without a header naming the columns for the remaining rows.
In <<performing-io-to-passing-data>>, we((("Commons CSV library")))((("Apache Commons CSV library"))) saw that one team had created its own parser; in other places, we use the tried-and-trusted https://oreil.ly/jnI4h[Apache Commons CSV library].
Honestly, for most uses, we would still use Commons CSV, because it works out of the box, is nicely configurable for special cases, and plays really well with Kotlin.

Today though we're going to see what a clean-room Kotlin parser would look like.
When we're done, we'll compare what we come up with to the Commons CSV functionality so that we can see how the grains of Java and Kotlin lead to different APIs and implementations.

[role="pagebreak-before"]
=== An Acceptance Test

As((("classes to functions", "acceptance tests", id="CFacc22")))((("acceptance tests", id="accept22"))) you might have been able to tell from the preceding chapters, the Travelator developers are Extreme Programmers (<<B_EPEEC_1999,_Extreme Programming Explained: Embrace Change_>>).
We write code test first, starting with a high-level acceptance test.
We're working on a table reader, so we create a class `TableReaderAcceptanceTests` with a stub method and check that it runs:

// begin-insert: table-reader.1:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt
[source,kotlin]
----
class TableReaderAcceptanceTests {
    @Test
    fun test() {
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.1&amp;show=file">Example 22.1 [table-reader.1:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.1&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It does run (it even passes!), so now we can start coding proper.

Part of the acceptance test's job is to help us decide what our interface should look like.
Having parsed a few files in our time, we know that what we almost always want to do is read a file and return a list of values of some domain type, one for each (nonheader) row.
Let's sketch that as our test, with `Measurement` as our domain type:

// begin-insert: table-reader.2:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt
[source,kotlin]
----
class TableReaderAcceptanceTests {
    data class Measurement(
        val t: Double,
        val x: Double,
        val y: Double,
    )

    @Test
    fun `acceptance test`() {
        val input = listOf(
            "time,x,y",
            "0.0,  1,  1",
            "0.1,1.1,1.2",
            "0.2,1.2,1.4",
        )
        val expected = listOf(
            Measurement(0.0, 1.0, 1.0),
            Measurement(0.1, 1.1, 1.2),
            Measurement(0.2, 1.2, 1.4)
        )
        assertEquals(
            expected,
            someFunction(input)
        )
    }

    private fun someFunction(input: List<String>): List<Measurement> {
        TODO("Not yet implemented")
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.2&amp;show=file">Example 22.2 [table-reader.2:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.2&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert


Here `Measurement` is a value type that represents the data that we want to extract from each row of the table.
In Java, we would probably start by creating a `TableReader` class, but we can see from the test that reading a table is simply a calculation: a mapping of the input lines to a list of the data that we want (<<calculations>>).
So we'll default to using a top-level `someFunction` until we are forced to do something more complicated.

We can imagine all sorts of magic ways that our API could implement `someFunction`, but unless it has some special knowledge of the `Measurement` type (and libraries don't have knowledge of _our_ types, that's the wrong way around), we will have to tell it how to map from some representation of a row to a `Measurement`.

That's twice we've used the word _map_.
Maybe _map_ holds the key?
(An accidental pun, that one.)
What if `someFunction` looked like this?

// begin-insert: table-reader.3:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#someFunction
[source,kotlin]
----
private fun someFunction(input: List<String>): List<Measurement> =
    readTable(input) // <1>
        .map { record -> // <2> <3>
        Measurement(
            record["time"].toDouble(), // <4>
            record["x"].toDouble(), // <4>
            record["y"].toDouble(), // <4>
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.3&amp;show=file">Example 22.3 [table-reader.3:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.3&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> `readTable` is our table reading API entry point
<2> It returns something that has a `map` implementation.
<3> `record` is our representation of a row in the table...
<4> We can index into `record` by field name, yielding a `String` that we can convert to other types.

This doesn't compile, because we don't have `readTable` yet, but if we Alt-Enter on the error, IntelliJ will create the function for us:

// begin-insert: table-reader.3:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#readTable
[source,kotlin]
----
private fun readTable(input: List<String>): Any {
    TODO("Not yet implemented")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.4&amp;show=file">Example 22.4 [table-reader.3:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.4&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We haven't given IntelliJ enough clues about the return type of `readTable`, so it chose `Any`, and so `someFunction` still doesn't compile.
What type could we return to fix that?
Well, if we return a `List` from `readTable`, then `map` is an operation on `List`.
And if that `List` contained `Map<String, String>`, our `record` variable would be `Map<String, String>`, so we could call `record["time"]`, and so on.
The only issue is that `Map.get` returns a nullable value.
That's close enough—let's take account of it in `someFunction` by raising errors if `get` returns `null`:

// begin-insert: table-reader.4:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#excerpt
[source,kotlin]
----
private fun someFunction(input: List<String>): List<Measurement> =
    readTable(input).map { record ->
        Measurement(
            record["time"]?.toDoubleOrNull() ?: error("in time"),
            record["x"]?.toDoubleOrNull() ?: error("in x"),
            record["y"]?.toDoubleOrNull() ?: error("in y"),
        )
    }

fun readTable(input: List<String>): List<Map<String, String>> {
    TODO("Not yet implemented")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.5&amp;show=file">Example 22.5 [table-reader.4:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.5&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This compiles, although obviously the `TODO` fails the test.
(You might ask why we are taking such a cavalier attitude toward errors compared to our forensic <<exceptions-to-values>>.
The answer is that this is just test code: the API of `Map.get` is forcing us to consider what to do in the case of errors, and our test is choosing to throw.)

We put our client hats on to write the acceptance tests, and these tests have shown that we can at least use a function with the signature of `readTable` to convert lines to a list of `Measurement`.
Now that we have a plausible API, we can move the definition of `readTable` into __src/main/travelator/tablereader/table-reading.kt__:

// begin-insert: table-reader.5:src/main/java/travelator/tablereader/table-reading.kt
[source,kotlin]
----
fun readTable(input: List<String>): List<Map<String, String>> {
    TODO("Not yet implemented")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.6&amp;show=file">Example 22.6 [table-reader.5:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.6&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Finally in this first stage, we can inline `someFunction` to give our acceptance test:

// begin-insert: table-reader.5:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#excerpt
[source,kotlin]
----
@Disabled
@Test
fun `acceptance test`() {
    val input = listOf(
        "time,x,y",
        "0.0,  1,  1",
        "0.1,1.1,1.2",
        "0.2,1.2,1.4",
    )
    val expected = listOf(
        Measurement(0.0, 1.0, 1.0),
        Measurement(0.1, 1.1, 1.2),
        Measurement(0.2, 1.2, 1.4)
    )
    assertEquals(
        expected,
        readTable(input).map { record ->
            Measurement(
                t = record["time"]?.toDoubleOrNull() ?: error("in time"),
                x = record["x"]?.toDoubleOrNull() ?: error("in x"),
                y = record["y"]?.toDoubleOrNull() ?: error("in y"),
            )
        }
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.7&amp;show=file">Example 22.7 [table-reader.5:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.7&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Note that we have disabled the test because it will be some time before we get it running.
That's OK with acceptance tests.
We don't expect to get them to pass quickly, more tell us when we are done.
For now, it has done its job, helping us sketch a simple API that we can now implement.

Before we do go on, let's reflect on the fact that we have managed to define the interface to our parser without defining any new types, instead using `List` and `Map` of `String`.
By using standard types, we know that we have rich Kotlin APIs to supply the `List` that we are reading from, and to interpret the `List` of ++Map++s that we are returning.((("", startref="CFacc22")))((("", startref="accept22")))

=== Unit Testing

Now((("classes to functions", "unit testing", id="CFunit22")))((("unit testing", id="unit22"))) that we have an interface to implement, we can park the acceptance test and write a minimal unit test.
What is minimal?
We like to start with empty: what should happen if we read an empty file?

// begin-insert: table-reader.6:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
class TableReaderTests {
    @Test
    fun `empty list returns empty list`() {
        val input: List<String> = emptyList()
        val expectedResult: List<Map<String, String>> = emptyList()
        assertEquals(
            expectedResult,
            readTable(input)
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.8&amp;show=file">Example 22.8 [table-reader.6:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.8&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

The simplest way to get this to pass is to hard-code the result in `readTable`:

// begin-insert: table-reader.7:src/main/java/travelator/tablereader/table-reading.kt
[source,kotlin]
----
fun readTable(input: List<String>): List<Map<String, String>> {
    return emptyList()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.9&amp;show=file">Example 22.9 [table-reader.7:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.9&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This passes.
It may seem trivial, but it's always a good idea to have a test for empty input. The more complicated our algorithm, the more likely it is to fail in this case.
It's a poor parser that always returns an empty result, though, so let's crack on.
Following((("TDD (Test Driven Development)"))) TDD (<<B_TDDBE_2002,_Test-Driven Development By Example_>>), we need to add a failing test first to give us a reason to change the implementation.
We choose to add the case of reading a table with no header and one line of data.

Why this rather than a header and one line of data?
To be honest, this is just the first thing that came to mind; maybe if we were actually pairing at this point, you would have suggested using a header row.
Our choice leaves us having to decide how to name the columns, and we decide to use the `String` representation of their index, `"0"` for the first column, `"1"` for the second, and so on; this feels like the simplest way that we can generate a `String` key:

// begin-insert: table-reader.8:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `empty list returns empty list`() {
    assertEquals(
        emptyList<Map<String, String>>(),
        readTable(emptyList())
    )
}

@Test
fun `one line of input with default field names`() {
    assertEquals(
        listOf(
            mapOf("0" to "field0", "1" to "field1")
        ),
        readTable(listOf(
            "field0,field1"
        ))
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.10&amp;show=file">Example 22.10 [table-reader.8:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.10&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We _could_ instead have made `readTable` return `<Map<Int, String>>` when we don't have a header row.
If you have some spare time, that might be a path worth following to see where it leads.

Back in our current predicament, we have a failing test, and we can be clever or we can be quick.
We choose quick, to get the test passing straightaway by hardcoding the result again:

// begin-insert: table-reader.8:src/main/java/travelator/tablereader/table-reading.kt
[source,kotlin]
----
fun readTable(lines: List<String>): List<Map<String, String>> {
    return if (lines.isEmpty())
        emptyList()
    else listOf(
        mapOf("0" to "field0", "1" to "field1")
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.11&amp;show=file">Example 22.11 [table-reader.8:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.11&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Now that our tests are passing, we can simplify the implementation by noticing that we want a line in the output for every line in the input.
`Iterable::map` will do this, allowing us to remove the `if` expression:

// begin-insert: table-reader.9:src/main/java/travelator/tablereader/table-reading.kt
[source,kotlin]
----
fun readTable(lines: List<String>): List<Map<String, String>> {
    return lines.map {
        mapOf("0" to "field0", "1" to "field1")
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.12&amp;show=file">Example 22.12 [table-reader.9:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.12&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This continues to pass the tests and would now work for more lines (of identical data)!
It's only a stepping-stone though, allowing us to extract the lambda as a [.keep-together]#function#:

// begin-insert: table-reader.10:src/main/java/travelator/tablereader/table-reading.kt
[source,kotlin]
----
fun readTable(lines: List<String>): List<Map<String, String>> {
    return lines.map(::parseLine)
}

private fun parseLine(line: String) = mapOf("0" to "field0", "1" to "field1")
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.13&amp;show=file">Example 22.13 [table-reader.10:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.13&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Now we'll start removing the hard-coded values by splitting the pairs into `keys` and `values`:

// begin-insert: table-reader.11:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val keys = listOf("0", "1")
    val values = listOf("field0", "field1")
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.14&amp;show=file">Example 22.14 [table-reader.11:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.14&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We're still resolutely cheating, but we can now see the pattern in the `keys` and generate these from the `values`:

// begin-insert: table-reader.12:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = listOf("field0", "field1")
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.15&amp;show=file">Example 22.15 [table-reader.12:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.15&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

For the `values`, we can split the line around the commas:

// begin-insert: table-reader.13:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = line.split(",")
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.16&amp;show=file">Example 22.16 [table-reader.13:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.16&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Success: we have removed the hard-coded keys and values, and the tests still pass.
Because we used `lines.map` in `readTable`, we believe the function will work for any numbers of lines, but it would be good to have a test to confirm that.

We make a note to add it, because something is bothering us that we'd like to look at first.
If you are as old as your authors (or younger and gifted) you may have developed spidey senses for code, and they may be tingling when you look at that `split`.
What will happen if we try to split an empty line?
For that matter, what should [.keep-together]#++readTable++# return when fed an empty line?

Discussing it, we come to the conclusion that an empty line should yield an empty `Map`.
That feels clean, so we write a test to both document our decision and check that it works:

// begin-insert: table-reader.14:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `empty line returns empty map`() {
    assertEquals(
        listOf(
            emptyMap<String, String>()
        ),
        readTable(listOf(
            ""
        ))
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.17&amp;show=file">Example 22.17 [table-reader.14:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.17&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Aha!

----
org.opentest4j.AssertionFailedError:
Expected :[{}]
Actual   :[{0=}]
----

After a little investigation, we discover that calling `split` on an empty `String` returns a `List` of a single empty `String`.
Maybe that makes sense in other circumstances.
Maybe, but it messes up our algorithm, so we have to work around it with a special case in `parseLine`:

// begin-insert: table-reader.14:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = if (line.isEmpty()) emptyList() else line.split(",")
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.18&amp;show=file">Example 22.18 [table-reader.14:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.18&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

That gets the tests passing but muddies the waters of the `parseLine` function.
So we extract the muddy line to a function called `splitFields`:

// begin-insert: table-reader.15:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = splitFields(line)
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}

private fun splitFields(line: String): List<String> =
    if (line.isEmpty()) emptyList() else line.split(",")
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.19&amp;show=file">Example 22.19 [table-reader.15:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.19&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

If we make `splitFields` an extension function and introduce a `separators` parameter, we get the function we always really wanted `split` to be:

// begin-insert: table-reader.16:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = line.splitFields(",")
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}

private fun String.splitFields(separators: String): List<String> =
    if (isEmpty()) emptyList() else split(separators)
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.20&amp;show=file">Example 22.20 [table-reader.16:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.20&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

So far, we have gotten the code working with an empty input and then an input of a single line.
If we had written an imperative solution, we might now have to add a loop to handle more input, but `map` has our back, because it will always return as many items as we give it.
We believe that `readTable` should work for all the numbers known to programmers: 0, 1, and infinity (well, OK, 2^31^ - 1 rather than actual infinity).

"Trust but verify" they say though, so we add a test:

// begin-insert: table-reader.17:src/test/java/travelator/tablereader/TableReaderTests.kt#twoLines
[source,kotlin]
----
@Test
fun `two lines of input with default field names`() {
    assertEquals(
        listOf(
            mapOf("0" to "row0field0", "1" to "row0field1"),
            mapOf("0" to "row1field0", "1" to "row1field1")
        ),
        readTable(listOf(
            "row0field0,row0field1",
            "row1field0,row1field1"
        ))
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.21&amp;show=file">Example 22.21 [table-reader.17:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.21&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It passes, and we reason that `(0, 1, 2)` is close enough to `(0, 1, 2147483647)` that we are done for now.
This seems like a good place to check in, make a fresh coffee, and dispose of the last one before getting back to work.((("", startref="CFunit22")))((("", startref="unit22")))

=== Headers

Ready((("classes to functions", "headers", id="CFheader22")))((("header lines", id="header22"))) to go again?
OK, what about a header line?

First, how should our API know to expect one?
We could add a flag to `readTable` to tell it that our data has a header, or we can add another function.
Generally we prefer a different function for different functionality, so let's add a function named `readTableWithHeader`.

As with `readTable`, we first add a test that calls the function that we wish we had:

// begin-insert: table-reader.18:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `takes headers from header line`() {
    assertEquals(
        listOf(
            mapOf("H0" to "field0", "H1" to "field1")
        ),
        readTableWithHeader(
            listOf(
                "H0,H1",
                "field0,field1"
            )
        )
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.22&amp;show=file">Example 22.22 [table-reader.18:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.22&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Alt-Enter on the compilation error at `readTableWithHeader` and IntelliJ will create it for us.
Then we can name the parameters and delegate to our original function for now:

// begin-insert: table-reader.18:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(lines)
}

fun readTable(lines: List<String>): List<Map<String, String>> {
    return lines.map(::parseLine)
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.23&amp;show=file">Example 22.23 [table-reader.18:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.23&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This compiles but fails the tests, as we expect:

----
org.opentest4j.AssertionFailedError:
Expected :[{H0=field0, H1=field1}]
Actual   :[{0=H0, 1=H1}, {0=field0, 1=field1}]
----

To get the tests to pass, we could hard-code the result as before, but this time we're going to modify the code to make room for the functionality.
When we say _make room_, what we are aiming for is code that does the current thing (using `Int::toString` field names) and which we are able to _augment_ rather than modify to support the new functionality.
The new feature will then be an addition _rather_ than a modification (the https://oreil.ly/MwO5l[open–closed principle]).

Currently, the field name information is buried in `parseLine`:

// begin-insert: table-reader.18:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = line.splitFields(",")
    val keys = values.indices.map(Int::toString)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.24&amp;show=file">Example 22.24 [table-reader.18:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.24&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We're going to pull it out from here to a place where we can use the header line to supply it.

`Int::toString` is our current mapping from index to key.
Let's prepare to make this configurable by introducing a variable named `headerProvider`:

// begin-insert: table-reader.19:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(line: String): Map<String, String> {
    val values = line.splitFields(",")
    val headerProvider: (Int) -> String = Int::toString
    val keys = values.indices.map(headerProvider)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.25&amp;show=file">Example 22.25 [table-reader.19:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.25&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This still passes our tests, except for the new `takes headers from header line`, which is still failing.
We shouldn't really be refactoring with a failing test, because every time we run the tests, we will have to check that any failure is actually the one we expect.
So we `@Disabled` it for now to only run tests for completed features while we are [.keep-together]#refactoring#.

"Introduce Parameter" on the `headerProvider` line and naming it `headerProvider` will allow us to support different behaviors:

// begin-insert: table-reader.20:src/main/java/travelator/tablereader/table-reading.kt#parseLine
[source,kotlin]
----
private fun parseLine(
    line: String,
    headerProvider: (Int) -> String
): Map<String, String> {
    val values = line.splitFields(",")
    val keys = values.indices.map(headerProvider)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.26&amp;show=file">Example 22.26 [table-reader.20:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.26&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Unfortunately, IntelliJ currently fails to make this refactor work, breaking `readTable`:

// begin-insert: table-reader.20:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(lines)
}

fun readTable(lines: List<String>): List<Map<String, String>> {
    return lines.map(::parseLine) // <1>
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.27&amp;show=file">Example 22.27 [table-reader.20:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.27&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> We could use the function reference when `parseLine` only had one parameter. Now it needs two arguments, but `map` can only supply one.

"Replace function reference with lambda" _before_ the refactor would have made everything work now, but we'll fail forward by expanding the lambda now and adding `Int::toString` as the `headerProvider` to get things compiling again:

// begin-insert: table-reader.21:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(lines)
}

fun readTable(lines: List<String>): List<Map<String, String>> {
    return lines.map { parseLine(it, Int::toString) }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.28&amp;show=file">Example 22.28 [table-reader.21:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.28&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

All our tests still pass, so we're quietly confident that we haven't broken anything.

Where are we going with this?
Our plan is to have the new `readTableWithHeader` read the header line to create a `headerProvider` to pass to `parseLine`.
Sitting between [.keep-together]#++readTableWithHeader++# and `parseLine` is the call to our old `readTable`, so it needs a `headerProvider` parameter too, so that it can relay the value.
So it's "Introduce Parameter" (with "Introduce Default Value") again, this time on `Int::toString` in `readTable`:

// begin-insert: table-reader.22:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(lines)
}

fun readTable(
    lines: List<String>,
    headerProvider: KFunction1<Int, String> = Int::toString // <1>
): List<Map<String, String>> {
    return lines.map { parseLine(it, headerProvider) }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.29&amp;show=file">Example 22.29 [table-reader.22:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.29&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> Doesn't compile: `Unresolved reference: KFunction1`

It's hard to say why IntelliJ (at the time of writing) sometimes uses function types and sometimes `KFunctionN` types when refactoring.
It would be nice if it was consistent, or at least generated code that compiled.
We'll fix this one by translating the `KFunction1` to an `(Int) -> String` by hand and hold just a little grudge for this second failed refactor in a row:

// begin-insert: table-reader.23:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(lines)
}

fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString
): List<Map<String, String>> {
    return lines.map { parseLine(it, headerProvider) }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.30&amp;show=file">Example 22.30 [table-reader.23:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.30&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

On the plus side, because the `headerProvider` parameter has a default value, our tests are unchanged and continue to pass.

Now we're in a position to parse the header line;
`readTableWithHeader` will need to read the header, create a `headerProvider` (an `(Int) -> String` remember), and then delegate to `readTable`.
It needs to split the lines into the header (`Iterable.first()`) and the rest (`Iterable.drop(1)`).
`Iterable.first` will fail if there are no lines, so we make a note to add a test for this case.
As for converting the header line into a ++header&#x200b;Pro&#x2060;vider++, we'll pretend that we have a function to do that called `headerProviderFrom(String)`:

// begin-insert: table-reader.24:src/main/java/travelator/tablereader/table-reading.kt#readTableWithHeader
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(
        lines.drop(1),
        headerProviderFrom(lines.first())
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.31&amp;show=file">Example 22.31 [table-reader.24:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.31&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Alt-Enter on the new function's invocation allows us to create it, giving:

// begin-insert: table-reader.24:src/main/java/travelator/tablereader/table-reading.kt#headerProviderFrom
[source,kotlin]
----
fun headerProviderFrom(header: String): (Int) -> String {
    TODO("Not yet implemented")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.32&amp;show=file">Example 22.32 [table-reader.24:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.32&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This is a function that needs to return a function type.
We can implement the return value with a lambda that takes an `Int` index and returns a `String`.
The `String` we need to return is the header field at that index.
We can use our `splitFields` again here:

// begin-insert: table-reader.25:src/main/java/travelator/tablereader/table-reading.kt#headerProviderFrom
[source,kotlin]
----
private fun headerProviderFrom(header: String): (Int) -> String {
    val headers = header.splitFields(",")
    return { index -> headers[index] }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.33&amp;show=file">Example 22.33 [table-reader.25:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.33&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We've taken care to split the `header` outside the lambda; otherwise, it will happen for every other row of the table.
Our tests still pass, and if we're right, so will the test for `readTableWithHeader` that we disabled previously.
Let's un-`@Disabled` it:

// begin-insert: table-reader.26:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `takes headers from header line`() {
    assertEquals(
        listOf(
            mapOf("H0" to "field0", "H1" to "field1")
        ),
        readTableWithHeader(
            listOf(
                "H0,H1",
                "field0,field1"
            )
        )
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.34&amp;show=file">Example 22.34 [table-reader.26:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.34&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This passes, hooray!
We are about to say that we're done for now, until we look down at our to-do list and remember that we predicted `readTableWithHeader` should fail given an empty input.
So we write a test asserting the desired behavior, which is to return an empty `List`:

// begin-insert: table-reader.26:src/test/java/travelator/tablereader/TableReaderTests.kt#empty
[source,kotlin]
----
@Test
fun `readTableWithHeader on empty list returns empty list`() {
    assertEquals(
        emptyList<String>(),
        readTableWithHeader(
            emptyList()
        )
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.35&amp;show=file">Example 22.35 [table-reader.26:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.35&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

As we thought, this fails with `java.util.NoSuchElementException: List is empty.`, because `readTableWithHeader` is trying to call `lines.first()` on an empty `List`:

// begin-insert: table-reader.25:src/main/java/travelator/tablereader/table-reading.kt#readTableWithHeader
[source,kotlin]
----
fun readTableWithHeader(lines: List<String>): List<Map<String, String>> {
    return readTable(
        lines.drop(1),
        headerProviderFrom(lines.first())
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.36&amp;show=file">Example 22.36 [table-reader.25:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.36&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Our irritation at not being finished is mitigated by being right about there being a problem!
The simplest fix is to split our function into two definitions, with a `when` to choose between them.
This passes all the tests and empties our to-do list.
Here, then, is our public API:

// begin-insert: table-reader.26:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first())
        )
    }

fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString
): List<Map<String, String>> =
    lines.map { parseLine(it, headerProvider) }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.37&amp;show=file">Example 22.37 [table-reader.26:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.37&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This is nice.
Our clients now can read with or without a header row.
But wait!
Looking at the code, we realize that if they want to specify their own field names for `readTable`, they can do this by overriding the default `headerProvider` in `readTable`.
We have a feature for free!
Let's write a test to demonstrate it:

// begin-insert: table-reader.27:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `can specify header names when there is no header row`() {
    val headers = listOf("apple", "banana")
    assertEquals(
        listOf(
            mapOf(
                "apple" to "field0",
                "banana" to "field1",
            )
        ),
        readTable(
            listOf("field0,field1"),
            headers::get
        )
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.38&amp;show=file">Example 22.38 [table-reader.27:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.38&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

See how easy it is to convert from a `List<String>` to our header provider function `(Int) -> String` with the method reference((("headers::get"))) `headers::get`?
This is an interesting way to view collections.
We can view:

[cols="1,1,1"]
|===
|Type|as function type|by

|`List<T>`|`(index: Int) -> T`|`List.get(index)`

|`Set<T>`|`(item: T) -> Boolean`|`Set.contains(item)`

|`Map<K, V>`|`(key: K) -> V?`|`Map.get(key)`|
|===

If we are able to express a dependency as one of these function types, then our clients, and our tests, can use standard collections to provide an implementation.

Now that we have implemented reading a table with a header, we are in a position to try running our acceptance test.
This was:

// begin-insert: table-reader.26:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#excerpt
[source,kotlin]
----
@Disabled
@Test
fun `acceptance test`() {
    val input = listOf(
        "time,x,y",
        "0.0,  1,  1",
        "0.1,1.1,1.2",
        "0.2,1.2,1.4",
    )
    val expected = listOf(
        Measurement(0.0, 1.0, 1.0),
        Measurement(0.1, 1.1, 1.2),
        Measurement(0.2, 1.2, 1.4)
    )
    assertEquals(
        expected,
        readTable(input).map { record ->
            Measurement(
                t = record["time"]?.toDoubleOrNull() ?: error("in time"),
                x = record["x"]?.toDoubleOrNull() ?: error("in x"),
                y = record["y"]?.toDoubleOrNull() ?: error("in y"),
            )
        }
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.39&amp;show=file">Example 22.39 [table-reader.26:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.39&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

The function that we thought we would call `readTable` when we wrote the test turns out to be `readTableWithHeader`, so we make the change and run the test:

// begin-insert: table-reader.27:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt#excerpt
[source,kotlin]
----
assertEquals(
    expected,
    readTableWithHeader(input).map { record ->
        Measurement(
            t = record["time"]?.toDoubleOrNull() ?: error("in time"),
            x = record["x"]?.toDoubleOrNull() ?: error("in x"),
            y = record["y"]?.toDoubleOrNull() ?: error("in y"),
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.40&amp;show=file">Example 22.40 [table-reader.27:src/test/java/travelator/tablereader/TableReaderAcceptanceTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.40&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It passes, and we ride the little dopamine hit to check in the code and take a coffee break.((("", startref="CFheader22")))((("", startref="header22")))

=== Different Field Separators

Returning((("classes to functions", "different field separators", id="CFdiff22")))((("field separators", id="field22"))) from coffee, we make a quick survey of the different places in Travelator that read tables.
Interestingly, we only have one use case that reads classic &#x22;comma&#x22;,&#x22;separated&#x22;,&#x22;variables&#x22; (with the quotes), but several need to use a semicolon as the field separator.
It seems that some French SQL Server export job is using semicolons and then saving the file with a __.CSV__ extension; maybe the _C_ is for çemicolon?
We'll address reading those next, but try to find an interface that will work with more complicated quoting and escaping rules.
To add flexibility, we need to identify an abstraction, as we did with the `headerProvider` previously.
What is the abstraction here?

Looking at the code, we see that the header and body parsing both call `splitFields`:

// begin-insert: table-reader.28:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
private fun headerProviderFrom(header: String): (Int) -> String {
    val headers = header.splitFields(",")
    return { index -> headers[index] }
}

private fun parseLine(
    line: String,
    headerProvider: (Int) -> String
): Map<String, String> {
    val values = line.splitFields(",")
    val keys = values.indices.map(headerProvider)
    return keys.zip(values).toMap()
}

private fun String.splitFields(separators: String): List<String> =
    if (isEmpty()) emptyList() else split(separators)
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.41&amp;show=file">Example 22.41 [table-reader.28:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.41&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Neither the header parsing nor the body parsing really want to depend on the details of how the splitting should happen, so let's abstract that behind a function `(String) -> List<String>`.
Why that signature rather than just parameterizing the character?

That's an interesting question, thank you for asking it.
Introducing a `separators` parameter to `parseLine` and `headerProviderFrom`, and eventually their callers `readTable` and `readTableWithHeader`, would be the simplest thing that we could do.
We get a lot more flexibility from using a function type, though, because we can hide all the details of separating, quoting, and escaping behind that signature.
In pre-lambda Java, the benefit of the flexibility wouldn't have been worth the cost of introducing and implementing a SAM interface, at least not until we really needed all that control.
With lambdas in Java, the equation feels more balanced but probably not natural for most Java programmers.
In Kotlin, designed from the outset with function types as part of the language, we use them even more readily.
As soon as we need to parameterize an aspect of our code, it is natural to ask whether a function would provide more value than, erm, a simple value.

Let's start in `parseLine`.
To extract the current splitting implementation, we can select `line.splitFields(",")` and "Introduce Functional Parameter", choosing the parameter name `splitter`:

// begin-insert: table-reader.29:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString
): List<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider) { line -> // <1>
            line.splitFields(",")
        }
    }

...

private fun parseLine(
    line: String,
    headerProvider: (Int) -> String,
    splitter: (String) -> List<String>, // <2>
): Map<String, String> {
    val values = splitter(line)
    val keys = values.indices.map(headerProvider)
    return keys.zip(values).toMap()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.42&amp;show=file">Example 22.42 [table-reader.29:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.42&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> This lambda...
<2> ...implements the splitter.

We could continue this process, extracting the splitter lambda to the top level.
Our lives will be made a bit easier, though, if we have a global value for the splitter, so we select the lambda in `readTable` and "Introduce Variable" named `splitOnComma`:

// begin-insert: table-reader.30:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString
): List<Map<String, String>> =
    lines.map {
        val splitOnComma: (String) -> List<String> = { line ->
            line.splitFields(",")
        }
        parseLine(it, headerProvider, splitOnComma)
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.43&amp;show=file">Example 22.43 [table-reader.30:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.43&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Now we can cut the `val` from the function and move it to the top level.
It feels like there should be an automated refactor for this, but nothing works at the time of writing:

// begin-insert: table-reader.31:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString
): List<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitOnComma)
    }

val splitOnComma: (String) -> List<String> = { line ->
    line.splitFields(",")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.44&amp;show=file">Example 22.44 [table-reader.31:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.44&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Now that `splitOnComma` is a global property, we can conveniently use it as a default.
We select the reference to it in `readTable` and then "Introduce Parameter", with "Introduce default value", calling the new parameter `splitter`.
This yields:

// begin-insert: table-reader.32:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitter)
    }

val splitOnComma: (String) -> List<String> = { line ->
    line.splitFields(",")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.45&amp;show=file">Example 22.45 [table-reader.32:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.45&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Because of the default value, we haven't had to change any of the clients, and the tests continue to pass.
As it stands, `readTable` is now using the supplied `splitter`, but `headerProviderFrom` is not:

// begin-insert: table-reader.32:src/main/java/travelator/tablereader/table-reading.kt#headerProviderFrom
[source,kotlin]
----
private fun headerProviderFrom(header: String): (Int) -> String {
    val headers = header.splitFields(",")
    return { index -> headers[index] }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.46&amp;show=file">Example 22.46 [table-reader.32:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.46&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Introducing a functional parameter for `header.splitFields(...)` yields:

// begin-insert: table-reader.33:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first()) { header -> // <1>
                header.splitFields(",")
            }
        )
    }

...

val splitOnComma: (String) -> List<String> = { line ->
    line.splitFields(",")
}

private fun headerProviderFrom(
    header: String,
    splitter: (String) -> List<String> // <2>
): (Int) -> String {
    val headers = splitter(header)
    return { index -> headers[index] }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.47&amp;show=file">Example 22.47 [table-reader.33:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.47&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> This lambda...
<2> ...implements the splitter.

Now the lambda in `readTableWithHeader` is the same code as `splitOnComma`, so we use that instead:

// begin-insert: table-reader.34:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitOnComma)
        )
    }

...

val splitOnComma: (String) -> List<String> = { line ->
    line.splitFields(",")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.48&amp;show=file">Example 22.48 [table-reader.34:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.48&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

You can see the pattern here.
Now we make a parameter from the `splitOnComma` reference, again with a default to avoid breaking existing clients:

// begin-insert: table-reader.35:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter)
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.49&amp;show=file">Example 22.49 [table-reader.35:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.49&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Finally, in `readTableWithHeader`, we are calling `readTable` without providing a `splitter`, so it will use its default (`splitOnComma`).
We don't want this, so we pass the parameter down.
The header and body should be using the same splitter, so we pass it from `readTableWithHeader` to the inner `readTable`:

// begin-insert: table-reader.36:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter // <1>
        )
    }

fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitter)
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.50&amp;show=file">Example 22.50 [table-reader.36:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.50&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> Pass on the `splitter`.

Some test-driven developers might insist on a failing test to show the need for that last step.
We certainly should write a test to demonstrate the use of the splitter, but before we do, let's make it more convenient to make one.
Here is `splitOnComma`:

// begin-insert: table-reader.36:src/main/java/travelator/tablereader/table-reading.kt#splitOnComma
[source,kotlin]
----
val splitOnComma: (String) -> List<String> = { line ->
    line.splitFields(",")
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.51&amp;show=file">Example 22.51 [table-reader.36:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.51&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It would be nice to be able to create splitters without having to define a lambda every time.
That way, our French clients could call `readTable` with, for example, `splitter = splitOn(";")`.
The `splitOn` function would take the separators and return a value of function type `(String) -> List<String>`.
We could try to extract this function from our current `splitOnComma` lambda, but the refactoring is tedious, so instead let's just define the function and call it:

// begin-insert: table-reader.37:src/main/java/travelator/tablereader/table-reading.kt#splitOnComma
[source,kotlin]
----
fun splitOn(
    separators: String
): (String) -> List<String> = { line: String ->
    line.splitFields(separators)
}

val splitOnComma: (String) -> List<String> = splitOn(",")
val splitOnTab: (String) -> List<String> = splitOn("\t")
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.52&amp;show=file">Example 22.52 [table-reader.37:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.52&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

You can see that we have taken the opportunity to define a `splitOnTab`, too, so that we can use it in the new test we promised ourselves that we would write:

// begin-insert: table-reader.38:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `can specify splitter`() {
    assertEquals(
        listOf(
            mapOf(
                "header1" to "field0",
                "header2" to "field1",
            )
        ),
        readTableWithHeader(
            listOf(
                "header1\theader2",
                "field0\tfield1"
            ),
            splitOnTab
        )
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.53&amp;show=file">Example 22.53 [table-reader.38:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.53&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This passes, giving us both reassurance and documentation.
Let's check it in and take a break for a few minutes before coming back to take stock.((("", startref="CFdiff22")))((("", startref="field22")))

=== Sequences

We((("classes to functions", "sequences", id="CFseq22")))((("sequences", id="seq22"))) now have the basics of a table parser, and we haven't introduced any new types beyond those in the standard Kotlin runtime.
This is often the way with a more functional approach.
The grain of Kotlin is to leverage the rich abstractions provided by the standard library, where Java programs are more likely to define new types.
As we saw in <<java-to-kotlin-collections>> and <<encapsulated-collections-to-typealiases>>, one reason for the difference is that Kotlin allows us to treat collections as values, which makes them more safely composable than Java's mutable objects.
We are able to define an API that takes and returns collection types without worrying about aliasing.

Value types may make for APIs composed of predictable calculations, but they can bring their own problems.
Our naïve API suffers from the same issue as we saw in <<performing-io-to-passing-data>>: it works on a `List<String>` loaded into memory and produces a `List<Map<String, String>>` also in memory.
Even discounting the cost of the data structures, the memory footprint of `readTable` is twice the number of bytes of the input, which is (probably) twice the size of a UTF-8 encoded file containing the data.
To process large files, it would be nice to work in terms of sequences rather than in terms of lists, since if-necessary sequences can keep only one item in each stage of a pipeline in memory at a time.

As we saw in <<streams-to-sequences>>, we can convert a `Sequence` to a `List` and back (with some caveats) very easily, so we could implement `Sequence` functions by delegating to our existing `List` API.
This wouldn't reduce our memory footprint though, so instead we'll write the `Sequence` versions and delegate the `List` versions to them.
If we're clever, we can test through the convenient `List` API, thus getting two sets of tests for the price of one.

`readTable` currently looks like this:

// begin-insert: table-reader.39:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitter)
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.54&amp;show=file">Example 22.54 [table-reader.39:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.54&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We can try out our plan by converting to and from `Sequence` in the middle of the pipeline:

// begin-insert: table-reader.40:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    lines
        .asSequence()
        .map {
            parseLine(it, headerProvider, splitter)
        }
        .toList()
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.55&amp;show=file">Example 22.55 [table-reader.40:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.55&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

That passes the tests, and they all funnel through this function, so that's reassuring.
Now we can extract the inner workings into a function taking and returning a `Sequence`; this is extracting part of a chain as described in <<extracting-part-of-a-pipeline>>:

// begin-insert: table-reader.41:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTable(
    lines: List<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    readTable(
        lines.asSequence(),
        headerProvider,
        splitter
    ).toList()

fun readTable(
    lines: Sequence<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
) = lines.map {
        parseLine(it, headerProvider, splitter)
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.56&amp;show=file">Example 22.56 [table-reader.41:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.56&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This gives us a `Sequence` version of `readTable` that the `List` version calls, and the `List` version is well tested.
Now for the outer `readTableWithHeader`.
It looks like this:

// begin-insert: table-reader.42:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.57&amp;show=file">Example 22.57 [table-reader.42:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.57&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Currently, `readTableWithHeader` is delegating to the `List` version of `readTable`.
If we want to produce a `Sequence` version (and we do), it should call the `Sequence` version of `readTable`, so we inline the call here to give:

// begin-insert: table-reader.43:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    when {
        lines.isEmpty() -> emptyList()
        else -> readTable(
            lines.drop(1).asSequence(),
            headerProviderFrom(lines.first(), splitter),
            splitter
        ).toList()
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.58&amp;show=file">Example 22.58 [table-reader.43:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.58&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Now, by hand, create a `linesAsSequence` as a variable and use it in place of `lines`.
This nearly works:

// begin-insert: table-reader.44:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> {
    val linesAsSequence = lines.asSequence()
    return when {
        linesAsSequence.isEmpty() -> emptySequence() // <1>
        else -> {
            readTable(
                linesAsSequence.drop(1),
                headerProviderFrom(linesAsSequence.first(), splitter),
                splitter
            )
        }
    }.toList()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.59&amp;show=file">Example 22.59 [table-reader.44:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.59&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

<1> Doesn't compile because there is no `Sequence<T>.isEmpty()`.

How do we tell if a `Sequence` is empty?
`linesAsSequence.firstOrNull() == null` does the trick:

// begin-insert: table-reader.45:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> {
    val linesAsSequence = lines.asSequence()
    return when {
        linesAsSequence.firstOrNull() == null -> emptySequence()
        else -> {
            readTable(
                linesAsSequence.drop(1),
                headerProviderFrom(linesAsSequence.first(), splitter),
                splitter
            )
        }
    }.toList()
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.60&amp;show=file">Example 22.60 [table-reader.45:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.60&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This passes the tests, so we can again extract the expression between the `return` and `.toList()` as the function we are looking for.
After extracting it and tidying up, we have the `Sequence` version of `readTableWithHeader`:

// begin-insert: table-reader.46:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
fun readTableWithHeader(
    lines: List<String>,
    splitter: (String) -> List<String> = splitOnComma
): List<Map<String, String>> =
    readTableWithHeader(
        lines.asSequence(),
        splitter
    ).toList()

fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
) = when {
    lines.firstOrNull() == null -> emptySequence()
    else -> {
        readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.61&amp;show=file">Example 22.61 [table-reader.46:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.61&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

At this point, we have two versions of `readTable` and `readTableWithHeader`: a `List` and a `Sequence` version of each.
Given how easy it is to convert a `List` argument to a `Sequence`, and a `Sequence` result to a `List`, maybe the `List` variants aren't paying their way?
Let's just move their definitions into the tests while we don't have any production uses.
That way, the tests can use them to stay simple, and the production code is kept minimal.

Here, then, is the entire public interface to our((("table parsers"))) table parser:

// begin-insert: table-reader.47:src/main/java/travelator/tablereader/table-reading.kt#public
[source,kotlin]
----
fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    when {
        lines.firstOrNull() == null -> emptySequence()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter
        )
    }

fun readTable(
    lines: Sequence<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitter)
    }

val splitOnComma: (String) -> List<String> = splitOn(",")
val splitOnTab: (String) -> List<String> = splitOn("\t")

fun splitOn(
    separators: String
) = { line: String ->
    line.splitFields(separators)
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.62&amp;show=file">Example 22.62 [table-reader.47:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.62&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This is supported by three utility functions:

// begin-insert: table-reader.47:src/main/java/travelator/tablereader/table-reading.kt#private
[source,kotlin]
----
private fun headerProviderFrom(
    header: String,
    splitter: (String) -> List<String>
): (Int) -> String {
    val headers = splitter(header)
    return { index -> headers[index] }
}

private fun parseLine(
    line: String,
    headerProvider: (Int) -> String,
    splitter: (String) -> List<String>,
): Map<String, String> {
    val values = splitter(line)
    val keys = values.indices.map(headerProvider)
    return keys.zip(values).toMap()
}

// Necessary because String.split returns a list of an empty string
// when called on an empty string.
private fun String.splitFields(separators: String): List<String> =
    if (isEmpty()) emptyList() else split(separators)
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.63&amp;show=file">Example 22.63 [table-reader.47:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.63&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

When we looked back at the code, we realized that it wasn't clear _why_ we needed `splitFields`, so we added a comment.
It's often easier to do this in retrospect when we are trying to understand code we are returning to, rather than code we have just written.
Apart from that, we think that the code is pretty self-explanatory.
Sometimes we're wrong about that.
If it takes us more than a glance to work out what is going on next time we read this code, we'll take the opportunity then to add more comments or, better, refactor to be more expressive.((("", startref="CFseq22")))((("", startref="seq22")))

=== Reading from a File

This((("classes to functions", "reading from files", id="CFread22")))((("files, reading from", id="fread22"))) seems a fine interface in the abstract, but the first time we come to use it in anger, we hit on a snag.
Let's illustrate the problem with a test.
This calls the `Sequence` version of `readTableWithHeader`:

// begin-insert: table-reader.48:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `read from reader`() {
    val fileContents = """
        H0,H1
        row0field0,row0field1
        row1field0,row1field1
    """.trimIndent()
    StringReader(fileContents).useLines { lines ->
        val result = readTableWithHeader(lines).toList()
        assertEquals(
            listOf(
                mapOf("H0" to "row0field0", "H1" to "row0field1"),
                mapOf("H0" to "row1field0", "H1" to "row1field1")
            ),
            result
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.64&amp;show=file">Example 22.64 [table-reader.48:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.64&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Can you see why this fails?
What if we say that it fails with `java.lang.IllegalStateException: This sequence can be consumed only once.`?

Yes, once again (<<sequences-multiple-operations>>), ++Sequence++s bite us because we didn't test both types—those that can and can't be consumed twice—as input:

// begin-insert: table-reader.47:src/main/java/travelator/tablereader/table-reading.kt#readTableWithHeader
[source,kotlin]
----
fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    when {
        lines.firstOrNull() == null -> emptySequence()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.65&amp;show=file">Example 22.65 [table-reader.47:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.65&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

So `lines.firstOrNull()` consumes the sequence, and when reading from a `Reader` we can't just go back and start again in order to evaluate `lines.drop(1)` and `lines.first()`.
Our unit tests were all starting from a `List` of all the file lines; those sequences  _can_ be consumed again, because they are held in memory.

To use our `Sequence` interface on data in files, we will either have to load it all into memory or find a way to fetch the first and rest of a `Sequence` without trying to read it twice.
Given that we introduced the `Sequence` specifically to avoid loading all the data into memory at once, we choose the latter.
All we need to do then is to check whether a `Sequence` has any items without consuming it.
Can you see how?

Ah, that one was a trick question.
To check, we _have_ to call `iterator()` on the `Sequence`, which is the very thing that consumes it.
We cannot see whether the `Sequence` is empty and then use it again later.
Sometimes in logic though, when we can't do a thing that we want in isolation, we can do it and another thing that we want together.
In this case, we don't just want to see whether the `Sequence` is empty; we want to split it into its head and tail if it isn't.
We can achieve that wider goal by destructuring the `Sequence` with a function like this:

// begin-insert: table-reader.49:src/main/java/travelator/tablereader/table-reading.kt#destruct
[source,kotlin]
----
fun <T> Sequence<T>.destruct()
    : Pair<T, Sequence<T>>? {
    val iterator = this.iterator()
    return when {
        iterator.hasNext() ->
            iterator.next() to iterator.asSequence()
        else -> null
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.66&amp;show=file">Example 22.66 [table-reader.49:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.66&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This `destruct` returns `null` if the `Sequence` is empty; otherwise, it returns a `Pair` of the head and the tail (where the tail may be an empty `Sequence`).
It consumes the original (by calling `iterator()`) but provides a fresh `Sequence` to continue processing.
We can use it to refactor `readTableWithHeader`, currently:

// begin-insert: table-reader.48:src/main/java/travelator/tablereader/table-reading.kt#readTableWithHeader
[source,kotlin]
----
fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    when {
        lines.firstOrNull() == null -> emptySequence()
        else -> readTable(
            lines.drop(1),
            headerProviderFrom(lines.first(), splitter),
            splitter
        )
    }
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.67&amp;show=file">Example 22.67 [table-reader.48:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.67&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It certainly isn't a trivial rearrangement, but we can transform this into:

// begin-insert: table-reader.49:src/main/java/travelator/tablereader/table-reading.kt#readTableWithHeader
[source,kotlin]
----
fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> {
    val firstAndRest = lines.destruct()
    return when {
        firstAndRest == null -> emptySequence()
        else -> readTable(
            firstAndRest.second,
            headerProviderFrom(firstAndRest.first, splitter),
            splitter
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.68&amp;show=file">Example 22.68 [table-reader.49:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.68&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

The new form passes all the tests, because it doesn't consume `lines` more than once.
If it feels a little clunky, we can combine a `?.let`, destructuring, and an Elvis operator to give a single expression that you may or may not find acceptably terse.
The result is this public API:

// begin-insert: table-reader.50:src/main/java/travelator/tablereader/table-reading.kt#public
[source,kotlin]
----
fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    lines.destruct()?.let { (first, rest) ->
        readTable(
            rest,
            headerProviderFrom(first, splitter),
            splitter
        )
    } ?: emptySequence()

fun readTable(
    lines: Sequence<String>,
    headerProvider: (Int) -> String = Int::toString,
    splitter: (String) -> List<String> = splitOnComma
): Sequence<Map<String, String>> =
    lines.map {
        parseLine(it, headerProvider, splitter)
    }

val splitOnComma: (String) -> List<String> = splitOn(",")
val splitOnTab: (String) -> List<String> = splitOn("\t")

fun splitOn(
    separators: String
) = { line: String ->
    line.splitFields(separators)
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.69&amp;show=file">Example 22.69 [table-reader.50:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.69&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We are almost done, we promise.

The last step, now that the API has crystallized around two functions, is to take the opportunity to make the tests more expressive:

// begin-insert: table-reader.52:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
class TableReaderTests {
    @Test
    fun `empty input returns empty`() {
        checkReadTable(
            lines = emptyList(),
            shouldReturn = emptyList()
        )
    }

    @Test
    fun `one line of input with default field names`() {
        checkReadTable(
            lines = listOf("field0,field1"),
            shouldReturn = listOf(
                mapOf("0" to "field0", "1" to "field1")
            )
        )
    }

    ...
    @Test
    fun `can specify header names when there is no header row`() {
        val headers = listOf("apple", "banana")
        checkReadTable(
            lines = listOf("field0,field1"),
            withHeaderProvider = headers::get,
            shouldReturn = listOf(
                mapOf(
                    "apple" to "field0",
                    "banana" to "field1",
                )
            )
        )
    }

    @Test
    fun `readTableWithHeader takes headers from header line`() {
        checkReadTableWithHeader(
            lines = listOf(
                "H0,H1",
                "field0,field1"
            ),
            shouldReturn = listOf(
                mapOf("H0" to "field0", "H1" to "field1")
            )
        )
    }

    ...
}

private fun checkReadTable(
    lines: List<String>,
    withHeaderProvider: (Int) -> String = Int::toString,
    shouldReturn: List<Map<String, String>>,
) {
    assertEquals(
        shouldReturn,
        readTable(
            lines.asSequence().constrainOnce(),
            headerProvider = withHeaderProvider,
            splitter = splitOnComma
        ).toList()
    )
}

private fun checkReadTableWithHeader(
    lines: List<String>,
    withSplitter: (String) -> List<String> = splitOnComma,
    shouldReturn: List<Map<String, String>>,
) {
    assertEquals(
        shouldReturn,
        readTableWithHeader(
            lines.asSequence().constrainOnce(),
            splitter = withSplitter
        ).toList()
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.70&amp;show=file">Example 22.70 [table-reader.52:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.70&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

This is an important step.
As we saw in <<mocks-to-maps>>, finding the patterns in our tests and expressing them in functions (like `checkReadTable`) both help readers of the tests to see what the code is doing and can help us find gaps in our test coverage.
For example, what is the behavior of our parser when there are more fields than headers or vice versa?
The tests that we write for quick feedback while we are test-driving our implementation are unlikely to be optimally effective for communicating about the API, finding issues, or catching regressions if we return to the implementation and modify it.
If we use TDD as a design technique, we mustn't forget to make sure that the final tests are fit for determining correctness, adding documentation, and preventing regression.((("", startref="fread22")))((("", startref="CFread22")))

=== Comparison with Commons CSV

We((("classes to functions", "comparison with Commons CSV", id="CFcomp22")))((("Commons CSV library", id="commonsCSV22")))((("Apache Commons CSV library", id="acoommonsCSV22"))) started this chapter by saying that in most real-world situations, we would reach for Apache Commons CSV rather than rolling our own parser.
Before we finish the chapter, let's compare our API with that of the Commons equivalent.

The most common use case for a table parser is to read a file with known columns, translating each row into some data class.
Here is how we do that with our parser:

// begin-insert: table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt#ours
[source,kotlin]
----
@Test
fun example() {
    reader.useLines { lines ->
        val measurements: Sequence<Measurement> =
            readTableWithHeader(lines, splitOnComma)
                .map { record ->
                    Measurement(
                        t = record["time"]?.toDoubleOrNull()
                            ?: error("in time"),
                        x = record["x"]?.toDoubleOrNull()
                            ?: error("in x"),
                        y = record["y"]?.toDoubleOrNull()
                            ?: error("in y"),
                    )
                }
        assertEquals(
            expected,
            measurements.toList()
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.71&amp;show=file">Example 22.71 [table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.71&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Real-world code would probably need more error handling (we see how in <<exceptions-to-values>>), but this shows the basic use case.
We use the Kotlin `Reader.useLines` extension function to produce a `Sequence<String>`, which our parser transforms into a `Sequence<Map<String, String>>`.
We can `map` over the ++Map++s, indexing by field name to extract the data we need and transform it to the type (`Measurement`) that we actually want.
This design didn't happen by accident—it was the decisions that we made at the very start, albeit with `List` rather than with `Sequence` at the time.

Here is the Commons CSV version:

// begin-insert: table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt#commons
[source,kotlin]
----
@Test
fun `commons csv`() {
    reader.use { reader ->
        val parser = CSVParser.parse(
            reader,
            CSVFormat.DEFAULT.withFirstRecordAsHeader()
        )
        val measurements: Sequence<Measurement> = parser
            .asSequence()
            .map { record ->
                Measurement(
                    t = record["time"]?.toDoubleOrNull()
                        ?: error("in time"),
                    x = record["x"]?.toDoubleOrNull()
                        ?: error("in x"),
                    y = record["y"]?.toDoubleOrNull()
                        ?: error("in y"),
                )
            }
        assertEquals(
            expected,
            measurements.toList()
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.72&amp;show=file">Example 22.72 [table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.72&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

It too has a static function entry point, `CSVParser.parse`, which also takes configuration about the table format (in this case, `CSVFormat.DEFAULT.withFirstRecordAsHeader()`; in ours, `splitOnComma`).
We have two functions to differentiate between files with or without headers; the Apache API rolls this into the `CSVFormat`.

The Commons `parse` takes a `Reader` though, rather than our `Sequence<String>`.
This allows it to handle record separators other than newline, and cope with having new lines in the middle of fields, but leads to a proliferation of `parse` methods. There are variants taking `Path`, `File`, `InputStream`, `String`, and `URL`.
The developers probably felt these were necessary because Java provides so little support for converting between these types of sources and disposing of them safely.
The `CSVParser` returned by the `parse` static method has a lot of code to manage resources.
Our API delegates these to the workings of `Sequence` and Kotlin life cycle functions like `use` and `useLines`.

On the subject of lines, you have to read between them in the code example to see it, but `CSVParser` implements `Iterable<CSVRecord>`.
This is a clever design choice, because it allows Java developers to use a `for` statement to loop over the records, and Kotlin developers to convert to a `Sequence` with `.asSequence`.
In fact, the Kotlin usability is due to the design of the Kotlin standard library, which builds on the same `Iterable` abstraction that the Apache developers also leverage.

Moving on, the code to create an individual `Measurement` looks identical in both examples:
// begin-insert: table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt#map
[source,kotlin]
----
.map { record ->
    Measurement(
        t = record["time"]?.toDoubleOrNull()
            ?: error("in time"),
        x = record["x"]?.toDoubleOrNull()
            ?: error("in x"),
        y = record["y"]?.toDoubleOrNull()
            ?: error("in y"),
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.73&amp;show=file">Example 22.73 [table-reader.53:src/test/java/travelator/tablereader/CsvExampleTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.73&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

Although the type of `record` in our parser is `Map<String, String>`, in the Commons case it is `CSVRecord`.
`CSVRecord` has a `get(String)` method, which is how `record["time"]` and so on are resolved.
It also has methods: `get(int)` to retrieve a field by index, where we could use `Map.values.get(Int)`;
`size()` rather than `Map.size()`; and `isSet(String)` to substitute for `Map.hasKey(String)`.

Basically, `CSVRecord` is having to reproduce the `Map` interface by hand rather than just _being_ a `Map`.
Why?
Because, as we discussed in <<java-to-kotlin-collections>>, the Java `Map` interface is mutable, and mutation makes no sense in the context of reading fields from a file; mutations certainly aren't going to be written back to the source.
When programming in Java, we find ourselves having to create new types to solve problems, where in Kotlin we can express ourselves in standard types and then enjoy the richness of the Kotlin API on those types.

One area in which the Commons CSV library Excels™️ is its provision of ready-made parser defaults.
These are expressed as constants in the `CSVFormat` class.
We've seen `CSVFormat.DEFAULT`, but there are many others, including `CSVFormat.EXCEL`.
Armed with a `CSVFormat`, you can pass it to the `CSVParser.parse` method as we saw, or use it directly, for example, `CSVFormat.EXCEL.parse(reader)`.
Can we provide this facility without defining new types in our API?
How about using `splitOnComma` as if it was our configuration:

// begin-insert: table-reader.54:src/test/java/travelator/tablereader/CsvExampleTests.kt#extension
[source,kotlin]
----
@Test
fun `configuration example`() {
    reader.use { reader ->
        val measurements = splitOnComma.readTableWithHeader(reader)
            .map { record ->
                Measurement(
                    t = record["time"]?.toDoubleOrNull()
                        ?: error("in time"),
                    x = record["x"]?.toDoubleOrNull()
                        ?: error("in x"),
                    y = record["y"]?.toDoubleOrNull()
                        ?: error("in y"),
                )
            }
        assertEquals(
            expected,
            measurements.toList()
        )
    }
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.74&amp;show=file">Example 22.74 [table-reader.54:src/test/java/travelator/tablereader/CsvExampleTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.74&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We can achieve this by defining `splitOnComma.readTableWithHeader(reader)` as an extension function on the function type:

// begin-insert: table-reader.54:src/main/java/travelator/tablereader/table-reading.kt#extension
[source,kotlin]
----
fun ((String) -> List<String>).readTableWithHeader(
    reader: StringReader
): Sequence<Map<String, String>> =
    readTableWithHeader(reader.buffered().lineSequence(), this)
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.75&amp;show=file">Example 22.75 [table-reader.54:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.75&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

In reality, `CSVFormat` represents a whole package of strategies for escaping rules, what to do with blank lines, and so on, not just how to split a line.
When our parser grows these facilities, then we will probably want to create a data class to collect them.
Until that point, we have been able to progress using just the built-in types and Kotlin language features.

There is another useful feature that the Commons interface provides that ours doesn't, and that we will finally need to create a type to implement.
Commons CSV has `CSVParser.getHeaderNames` to provide access to the header information.
Can we add this facility without modifying our current API, or at least requiring changes to our client code?

For many inputs, we could just call `Map.keys` on the first of the output `Sequence`, but this won't work if the table has no data rows, only a header.
To return header information _and_ the parsed records, we could return a `Pair<List<String>, Sequence<Map<String, String>>`, but this will force our current clients to discard the first of the pair.
Instead, we can return a type `Table` that implements `Sequence<Map<String, String>>` but also has a header property.
This way, all our current callers remain unchanged, but we can access `headers` when required:

// begin-insert: table-reader.55:src/test/java/travelator/tablereader/TableReaderTests.kt#excerpt
[source,kotlin]
----
@Test
fun `Table contains headers`() {
    val result: Table = readTableWithHeader(
        listOf(
            "H0,H1",
            "field0,field1"
        ).asSequence()
    )
    assertEquals(
        listOf("H0", "H1"),
        result.headers
    )
}

@Test
fun `Table contains empty headers for empty input`() {
    assertEquals(
        emptyList<String>(),
        readTableWithHeader(emptySequence()).headers
    )
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.76&amp;show=file">Example 22.76 [table-reader.55:src/test/java/travelator/tablereader/TableReaderTests.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.76&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

We'll spare you the refactoring steps, but here is the implementation:

// begin-insert: table-reader.55:src/main/java/travelator/tablereader/table-reading.kt#excerpt
[source,kotlin]
----
class Table(
    val headers: List<String>,
    val records: Sequence<Map<String, String>>
) : Sequence<Map<String, String>> by records

fun readTableWithHeader(
    lines: Sequence<String>,
    splitter: (String) -> List<String> = splitOnComma
): Table =
    lines.destruct()?.let { (first, rest) ->
        tableOf(splitter, first, rest)
    } ?: Table(emptyList(), emptySequence())

private fun tableOf(
    splitter: (String) -> List<String>,
    first: String,
    rest: Sequence<String>
): Table {
    val headers = splitter(first)
    val sequence = readTable(
        lines = rest,
        headerProvider = headers::get,
        splitter = splitter
    )
    return Table(headers, sequence)
}
----
++++
<div class="coderef">
    <a class="orm:hideurl" href="https://java-to-kotlin.dev/code.html?ref=22.77&amp;show=file">Example 22.77 [table-reader.55:src/main/java/travelator/tablereader/table-reading.kt]</a> <a class="orm:hideurl print-hide" href="https://java-to-kotlin.dev/code.html?ref=22.77&amp;show=diff">(diff)</a> 
</div>
++++
// end-insert

=== Moving On

In((("", startref="CFcomp22")))((("", startref="commonsCSV22")))((("", startref="acoommonsCSV22"))) this final leg of our journey, we allowed ourselves the luxury of writing Kotlin from scratch rather than refactoring our existing Java.
Even then, we started from the tests and then just copied the test data into our implementation and refactored from there.
We can't write all code this way, but it does work well when our code is just calculations, and the more of it that is just calculations, the better our code works, too.

We saw the power of reusing built-in types in pass:[<a data-type="xref" data-xrefstyle="chap-num-title" href="#encapsulated-collections-to-typealiases">#encapsulated-collections-to-typealiases</a>], and pass:[<a data-type="xref" data-xrefstyle="chap-num-title" href="#interfaces-to-functions">#interfaces-to-functions</a>], and defining APIs as extension functions in pass:[<a data-type="xref" data-xrefstyle="chap-num-title" href="#functions-to-extension-functions">#functions-to-extension-functions</a>].
In this example, both collection and function types came together nicely, and we even managed to define an extension function on a function type!
Where we would have had to define new classes to encapsulate Java's mutable collections, and methods to manipulate those collections, we passed Kotlin's immutable collections between our functions and wrote application-specific extensions on those collection types.
Where we would have needed to define interfaces in Java, we used Kotlin's function types.

[role="pagebreak-before"]
Again, not all problems can or should be solved this way, but your authors have found that while it is hard to make Java bend in this direction, Kotlin features combine to actively encourage this style.
We shouldn't get hung up on not defining new types, but neither should we leap to solve every problem with a new class.
