@startuml


Any <|-- String
Any <|-- Int

Any <|-- Fruit
Fruit <|-- Apple
Fruit <|-- Apple

interface ICanGoInASalad
Any <|-- ICanGoInASalad

interface ICanBeSunDried
Any <|-- ICanBeSunDried

Fruit <|-- Tomato
ICanGoInASalad <|-- Tomato
ICanBeSunDried <|-- Tomato

"Any?" <|-left- Any

"String?" <|-left- String
"Any?" <|-- "String?"

"Int?" <|-left- Int
"Any?" <|-- "Int?"

"Any?" <|-- "Fruit?"
"Fruit?" <|-- "Apple?"
"Fruit?" <|-- "Orange?"

interface "ICanGoInASalad?"
"Any?" <|-- "ICanGoInASalad?"
interface "ICanBeSunDried?"
"Any?" <|-- "ICanBeSunDried?"
"Fruit?" <|-- "Tomato?"
"ICanGoInASalad?" <|-- "Tomato?"
"ICanBeSunDried?" <|-- "Tomato?"

"Fruit?" <|-left- Fruit
"Apple?" <|-left- Apple
"Orange?" <|-left- Orange
"Tomato?" <|-left- Tomato
"ICanGoInASalad?" <|-left- ICanGoInASalad
"ICanBeSunDried?" <|-left- ICanBeSunDried

Any <|-- Unit
"Unit?" <|-left- Unit
"Any?" <|-- "Unit?"

String <|-- Nothing
Int <|-- Nothing
Unit <|-- Nothing
Apple <|-- Nothing
Orange <|-- Nothing
Tomato <|-- Nothing

"Nothing?" <|-left- Nothing

"String?" <|-- "Nothing?"
"Int?" <|-- "Nothing?"
"Unit?" <|-- "Nothing?"
"Apple?" <|-- "Nothing?"
"Orange?" <|-- "Nothing?"
"Tomato?" <|-- "Nothing?"

String -right[hidden]- Int
Int -right[hidden]- Unit
Unit -right[hidden]- Fruit

Fruit -right[hidden]- ICanGoInASalad
ICanGoInASalad -right[hidden]- ICanBeSunDried

Apple -right[hidden]- Orange
Orange -right[hidden]- Tomato

"String?" -right[hidden]- "Int?"
"Int?" -right[hidden]- "Unit?"
"Unit?" -right[hidden]- "Fruit?"

"Fruit?" -right[hidden]- "ICanGoInASalad?"
"ICanGoInASalad?" -right[hidden]- "ICanBeSunDried?"

"Apple?" -right[hidden]- "Orange?"
"Orange?" -right[hidden]- "Tomato?"

@enduml
