@startuml

interface "Juicer<Fruit>" {
    juice(Fruit) -> Liquid
}

interface "Juicer<Apple>" {
   juice(Apple) -> Liquid
}

interface "Juicer<Orange>" {
   juice(Orange) -> Liquid
}

"Juicer<Apple>" <|-- "Juicer<Fruit>"
"Juicer<Orange>" <|-- "Juicer<Fruit>"



@enduml
