@startuml

interface "Box<Fruit>" {
    put(Fruit)
    get() -> Fruit
}

together {
    interface "Box<Orange>" {
        put(Orange)
        get() -> Orange
    }

    interface "Box<Apple>" {
        put(Apple)
        get() -> Apple
    }
}

@enduml
