@startuml


interface "Source<Fruit>" {
    take() -> Fruit
}

interface "Source<Apple>" {
    take() -> Apple
}

interface "Source<Orange>" {
    take() -> Orange
}

"Source<Fruit>" <|-- "Source<Orange>"
"Source<Fruit>" <|-- "Source<Apple>"

@enduml
