@startuml


interface "Supplier<Fruit>" {
    receive() -> Fruit
}

interface "Supplier<Apple>" {
    receive() -> Apple
}

interface "Supplier<Orange>" {
    receive() -> Orange
}

"Supplier<Fruit>" <|-- "Supplier<Orange>"
"Supplier<Fruit>" <|-- "Supplier<Apple>"

@enduml
