@startuml

interface "Box<Fruit>" {
    put(Fruit)
    take() -> Fruit
}

together {
    interface "Box<Orange>" {
        put(Orange)
        take() -> Orange
    }

    interface "Box<Apple>" {
        put(Apple)
        take() -> Apple
    }
}

@enduml
