@startuml

Any <|-- Fruit
interface ICanGoInASalad
interface ICanGoInASalad
Any <|-- ICanGoInASalad
Any <|-- ICanBeSunDried
Fruit <|-- Tomato
ICanGoInASalad <|-- Tomato
ICanBeSunDried <|-- Tomato

@enduml
