@startuml

Any <|-- String
Any <|-- Int

Any <|-- Fruit
Fruit <|-- Apple
Fruit <|-- Orange

Any <|-- Unit

String <|-- Nothing
Int <|-- Nothing
Unit <|-- Nothing
Apple <|-- Nothing
Orange <|-- Nothing

String -right[hidden]- Int
Int -right[hidden]- Unit
Unit -right[hidden]- Fruit

@enduml
