@startuml

Any <|-- Fruit
Fruit <|-- Apple
Fruit <|-- Orange

"Any?" <|-- "Fruit?"
"Fruit?" <|-- "Apple?"
"Fruit?" <|-- "Orange?"

"Any?" <|-left- Any
"Fruit?" <|-left- Fruit
"Apple?" <|-left- Apple
"Orange?" <|-left- Orange

Apple -right[hidden]- Orange
"Apple?" -right[hidden]- "Orange?"

@enduml
